---
- name: Onboard a new user
  hosts: all
  become: yes
  vars:
    username: "{{ username }}"
    full_name: "{{ full_name }}"
    ssh_key: "{{ ssh_key }}"
  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        comment: "{{ full_name }}"
        shell: /bin/bash"
        groups: sudo
        state: present
        create_home: yes

    - name: Add authorized key
      authorized_key:
        user: "{{ username }}"
        key: "{{ ssh_key }}"

    - name: Create welcome file
      copy:
        dest: "/home/{{ username }}/WELCOME.txt"
        content: "Welcome to the team, {{ full_name }}!"
        owner: "{{ username }}"
        mode: '0644'
